### ISSUE TITLE
False+ on [Bug 1209192]

### ISSUE THREAD

**Issue by panossot** [jboss-set/bug-clerk#12]
There is a file attached with a commit.
Not allowed to make PR in the repo.
Bug-Clerk detects it as an error.

**Comment by rpelisse** [comment]
Thanks for the report ! :)

It's a known issue, but for now, I opt to live with it, because I am afraid if BugClerk ignores BZ with "commit" in the comment, it might just missed a lot of issue. 

Rather some False + than a lot of False - if you want. I'll keep the issue open, maybe, down the road, there will be an easy fix for that....
