### ISSUE TITLE
ReleaseVersionMismatch doesn't get release version correctly?

### ISSUE THREAD

**Issue by TomasHofman** [jboss-set/bug-clerk#32]
Check https://bugzilla.redhat.com/show_bug.cgi?id=1167348

BugClerk says:

"[ReleaseVersionMismatch] Release in title does not match actual release (6.3.0]:(6.4.0) ...bz title"

But "target release" in that BZ is set to "EAP 6.4.0". Is that legit?

**Comment by rpelisse** [comment]
Not, it's not, but it seems to be a bug in Aphrodite, rather than Bugclerk.

Indeed, on this issue issue.getReleases() returns this array "[Release{version='6.3.0', milestone='ER1'}]" which matches the content of the field "version" rather than the content of target release.

I'll open an issue on Aphrodite and fix it there.

**Comment by rpelisse** [comment]
Link to the Aphrodite issue : https://github.com/jboss-set/aphrodite/issues/88

**Comment by rpelisse** [comment]
This has been fixed in Aphrodite and will be fixed in the upcoming release of Bugclerk: 0.9.0.
