### ISSUE TITLE
Check Request #28 - check PR details with streams

### ISSUE THREAD

**Issue by soul2zimate** [jboss-set/bug-clerk#39]
check PR details (repository, branch, etc..) in help with stream service in Aphrodite.

**Comment by rpelisse** [comment]
@soul2zimate just saw this request - isn't it supposed to be part of Aphrodite rather than BugClekr ?

**Comment by soul2zimate** [comment]
I remember this one was opened after your presentation on a Friday.
Aphrodite does not check anything, it loads the stream service and allows other tools to implement any logic with it.

**Comment by baranowb** [comment]
How would it work? Work flow and example chechks? @soul2zimate ?

**Comment by rpelisse** [comment]
@soul2zimate OK, thinking about it, here is what I think was meant by this check request.

Whenever an issue has PR attached the check could look for the repo in jboss-streams and check that the PR is filled against the right branch.

So if we take https://github.com/jbossas/jboss-eap7/pull/293 as an example. This PR has been filed against the repo https://github.com/jbossas/jboss-eap7 and for this one, jboss-streams states that the codebase should 7.x.

However, in this case jboss-streams seems to be somewhat inconsistent as the right branch appears to be jbossas:7.x.

Is this what you though about when you open this request ? And how do we tackle inconsistency such as the one below ?

**Comment by soul2zimate** [comment]
The example PR in your comment is fine, https://issues.jboss.org/browse/JBEAP-1913 is a 7.1.0 issue, and the PR is for jbossas/jboss-eap7 branch 7.x. It's same one as defined in https://github.com/jboss-set/jboss-streams/blob/master/streams.json#L126 

An example https://bugzilla.redhat.com/show_bug.cgi?id=1177423 comment 1:

> On 2015-03-25 22:58:29 CST
> PR sent : https://github.com/jbossas/jboss-eap/pull/2369
> Status: ASSIGNED → POST

https://github.com/jbossas/jboss-eap/pull/2369 moves the issue from ASSIGNED to POST, but it is for 6.x branch which is incorrect as per https://github.com/jboss-set/jboss-streams/blob/master/streams.json#L348 

It should be opened for 6.4.x branch as updated in comment 4:

> 2016-10-20 16:12:40 CST
> 6.4.x PR : https://github.com/jbossas/jboss-eap/pull/2864

**Comment by rpelisse** [comment]
@soul2zimate I'm (finally) starting to work on the implementation of this check, and I am not sure we can implement it in fact. Let me walk you through my though process, so that you can correct me if I'm wrong.

The goal is here is to detect a discrepency between the Target Release field (ex: 6.4.10, 7.1.0.GA) and the branch a PR is being filled against (6.4.x, 7.1.x). So if one fills a PR against 6.x, instead of 6.4.x, for a 6.4.12 issue, this will be reported by Bugclerk.

To link a target release to a branch we have all the metadata available in jboss-streams. For instance, we can associate the target release 6.4.12 with the entry ["name": "jboss-eap-6.4.z"](https://github.com/jboss-set/jboss-streams/blob/master/streams.json#L7126). However, once we are there we need to locate the component to be associate with, and this is when we run into trouble.

AFAIU, there is inconsistency between jboss-streams names and the one used on JIRA (and probably also BZ, but did not check). For exemple

- JIRA has a component "logging" while the streams have 'jboss-logging'
- JIRA has a component "XML Frameworks" which not mapping directly to one component streams, and most likely involved several sub-projects.

Did I misunderstand something here ? Maybe you had in mind a simplier way to match the branches to pr ?

**Comment by soul2zimate** [comment]
component names in streams are not same as Jira/Bugzilla field "component", they're collection of sub projects/components of whole EAP, and are much more (over 100 after recent change) than the choices in Jira/Bugzilla.  And a general "component" in Jira like "management domain" can reflect more than one sub-project. 

[AESH](https://github.com/jboss-set/jboss-streams/blob/master/streams.json#L7130) and [DMR](https://github.com/jboss-set/jboss-streams/blob/master/streams.json#L7152) or even [wildfly-core](https://github.com/jboss-set/jboss-streams/blob/master/streams.json#L7041) are dependencies of EAP, there is no such value in Jira component list. However, a PR to these components repositories targeting correct branch might be the real fix of an issue.(Yes, a component upgrade PR is needed as well in component upgrade issue). 

The process could be something like: First, identify issue stream with target release. Then, if one or more than one PR resolves (Modified) the issue or update to pull request send (Post), tool compares each PR repository and branch to what have been defined in values "repository_url" and "codebase" in related stream. In any of unmatching, the suspicious PR reports a warning as someone might added incorrect PR which aims to different branch. And it changed the issue status. 

Although, it's possible that data in streams.json are out of date in the future, in such case, the warning is harmless and we need to update streams.json to the latest.

**Comment by rpelisse** [comment]
Good point, we can indeed iterate on all the Github and figure out if all the PR are part of any of them. I'll do that then ! :)

**Comment by baranowb** [comment]
We have to implement "auto update" to streams.json. When PR is merged, we have to check tareget stream name, update tag and update latest component version. This would require certain metadata to be present in PR. I was thinking that we would require another project, but bugclerk is most likely best spot for it. I will give it a go. Just need to get up2speed with code.


WRT names in streams. Yep, they dont match, with latest update it is even "worse" as those names are derived from PROD resources and match ${organization-unit}-${project-name}

**Comment by rpelisse** [comment]
Well, maybe let me finish implements this check, and you can then use this as a base for your "auto-update" ? At first glance, I'm not sure if Bugclerk is the right place for it, but maybe you are right, it is.

**Comment by rpelisse** [comment]
I've implemented a first minimal version of this [check](https://github.com/jboss-set/bug-clerk/commit/fb7198844b24c772861d8b4713d6cef961c69b74), howver it sadly needs code changes only available in Aphrodite 0.6.0-SNAPSHOT, so it will be released with Bugclerk 1.0.0, no 0.10.0...
