### ISSUE TITLE
Check Request #26 - Detect changes in issue once it is in resolved state

### ISSUE THREAD

**Issue by baranowb** [jboss-set/bug-clerk#43]
Once issue is "resolved" no changes should be allowed, no PRs linked, no state change. Unless it happens, all sirens should flare up, example:  https://issues.jboss.org/browse/JBEAP-5271   ( all view )
Jan Blizňák made changes - 11/Aug/16 7:55 AM

**Comment by MMarus** [comment]
Hi, I was thinking about the detection of the changes in issues in resolved state.
Is it mainly about the creation of *.drl rules and tests for them ?

I am not sure about what kind of changes should flare up the sirens.
Addition of the PR after issue is in resolved state is obvious, however the change of state is the one I am not sure about. What kind of change of state it should be ?
Because I think for example the change of state from "Resolved" to "Ready for QA" and from "Ready for QA" to "Verified" are allowed.

**Comment by baranowb** [comment]
Not sure about first part. Second, with transition is correct.
Imagine that you have upgrade JIRA, all fixes have been merged, you get tag from dev, tell prod to do magic and give you artifacts. All while someone link another fix to upgrade JIRA(this can happen later on). Unless this new  JIRA is also pushed into Sprint it will dangle unless RC notices it.

**Comment by rpelisse** [comment]
Implemented ! Will be part of 1.0.0 release.
