### ISSUE TITLE
Check Request #25 - Detect Fix version change once Sprint is set up.

### ISSUE THREAD

**Issue by baranowb** [jboss-set/bug-clerk#44]
When sprint is up for CP, no version changes should be allowed, unless RC or GSS perform them.
ie. if Sprint 7.0.6 ( payload freeze) is up, any change of fix version in range [7.0.6 CR1,...) can't be performed by any other party than RC or GSS(?) ? If it happens, alarm should sound.

**Comment by rpelisse** [comment]
@baranowb this might be quite difficult to implement, first because Bugclerk has no knowledge of time, so it can't react on state changes, which means, it needs to parses history of the issues, which is not (unless I am wrong) propagated through Aphrodite. 

We could definelty update Aphrodite to give access to the history of an issue, but I am afraid this would lead to loading a lot of data (and will require to implements some sort of lazy-loading). Also, writing the rule itself (search for changes in the version field in the history and then check if it happened after the Sprint date was set) is going to be very difficult with the MVEL syntax given by Drools. 

On top of it, comes the issue of the Whitelist - where does it lives ? Who / how do we maintains it ? 

I'm not saying I don't want to do it or that we should not, but just want to point out, it's not something for which Bugclerk is currently well designed for....

**Comment by rpelisse** [comment]
@baranowb Sleeping over it, I kind of made my mind. I think we do need such feature but other check request (like https://github.com/jboss-set/bug-clerk/issues/43) will need it. However this is going to be a bigger change to BugClerk/Aphrodite than what I had planned for this week. 

Thus, I'll postpone this change (and the forementioned check request) to 1.0.0, which I hope to be working on next week.

**Comment by rpelisse** [comment]
FYI, I'm still unsure where this "white list" lives (or should live) so I'm going to look at the past 6 month, see a bit who is changing those fix version generally...

**Comment by baranowb** [comment]
Where/how it is just a secondary problem. Whit elist most likely should include RCs.

**Comment by rpelisse** [comment]
Well, I do need to know where it  is from a programming point of view :)

Like do I pass a file path to the program ? Do I look up data from an URL ? Or should this be somehow provided by Aphrodite ?

**Comment by baranowb** [comment]
streams+aprhodite does not sound that bad.

**Comment by rpelisse** [comment]
So the information could live in Streams then? But we have to add it right ? Right now I don't see anything related to RC ? (or maybe I missed something) ?

**Comment by baranowb** [comment]
Most likely, but at the moment I would like things to settle to new streams.

**Comment by rpelisse** [comment]
Ok, so this feature needs for the RC information to made it to Aphrodite, through the Streams. Should we open an issue on Streams about that, and link this one to it ?

**Comment by rpelisse** [comment]
A [check](https://github.com/jboss-set/bug-clerk/commit/72407661b471bbd8f541bb75d66cb2d276dc6bf1) has been implemented to verify that state is no longer changed when issue is resolved. This will be released has part of the 1.0.0.
