### ISSUE TITLE
FixVersionAndSprintMustMatchBetweenSiblings#fixVersionAndSprintNotMatchingBetweenSiblings is wrong

### ISSUE THREAD

**Issue by baranowb** [jboss-set/bug-clerk#94]
As is, it is false pass. It does check on  Issue.getReleases() in Rules Helper. Test does:
Mockito.when(sibling.getSprintRelease()).thenReturn(sprintId);
sibling.setReleases(CollectionUtils.asListOf(sevenOhTwo));        

Name suggests sprint checks, which are not in place(?). As is, it passes since sibling.setRelease does nothing, since its mockied object, thus empty collection is returned(?) thus no trigger.

( not going to add mock, since Im not sure what this should test after all - oh boy, comments would be nice :) )

**Comment by rpelisse** [comment]
@baranowb I don't think the issue is the lack of comment ;) but more the lack of clarity / context on the description of the [original issue](https://github.com/jboss-set/bug-clerk/issues/83) ! 

The mock are supposed to mock JIRA/BZ, so whatever one mocks it should match what the trackers returns. 

I'm not sure what you mean by "It does check on Issue.getReleases() in Rules Helper". but that part is weird "As is, it passes since sibling.setRelease does nothing, since its mockied object, thus empty collection is returned(?) thus no trigger.". In my experience witch Mockito, if you call something that has not been mocked, it should complains., You should change the mocking here to return something and thus make the test fails.

**Comment by rpelisse** [comment]
@baranowb circling back on the issue of missing comments, can you do a PR with empty comment where you think we should have them ? (and tell a bit what you would like to see in those comment) As you know, I'm not a big fan of commenting code, but maybe if I see what you feel is missing, it will convert me :)
